### ISSUE TITLE
Donations Page

### ISSUE THREAD

**Issue by tiefpunkt** [munichmakerlab/website#3]
Page with infos on how to donate. Maybe also as contribution page and incl Membership form

**Comment by cecukemon** [comment]
https://www.munichmakerlab.de/about.html has information on how to donate, and a download link to the membership form. I guess this issue can be closed.

**Comment by Simmarith** [comment]
Issue seems to be ancient - Got fixed by @tiefpunkt 25.11.2014 in [this](https://github.com/munichmakerlab/website/commit/c04653c6ad4c4f781e19155b96f47e5919563c4b) commit.
